# Generated by Django 4.1.1 on 2022-09-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="member",
            name="email",
        ),
        migrations.AddField(
            model_name="member",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="member",
            name="pfp_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="member",
            name="social_links",
            field=models.ManyToManyField(blank=True, to="member.membersociallink"),
        ),
    ]
