# Generated by Django 4.1.1 on 2022-09-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_membersociallink_remove_member_email_member_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
