# Generated by Django 4.1.1 on 2022-09-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_member_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberaddress",
            name="ens",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
